name: Build & Upload

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
          arguments: build

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: NiaMod
          path: build/libs/*.jar

      - name: Upload jar to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          JAR_FILE=$(find build/libs -name "*.jar" | head -n 1)
          SHORT_SHA="${GITHUB_SHA::7}"
          COMMIT_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"

          COMMIT_SUBJECT=$(git log -1 --pretty=%s)
          COMMIT_DESCRIPTION=$(git log -1 --pretty=%b)

          CONTENT="New NiaMod commit: [\`${SHORT_SHA}\`](<${COMMIT_URL}>)

          Commit Subject: ${COMMIT_SUBJECT}"

          PAYLOAD_JSON=$(jq -n --arg content "$CONTENT" '{content: $content}')

          curl --fail -X POST "$DISCORD_WEBHOOK_URL" \
            -F "payload_json=${PAYLOAD_JSON}" \
            -F "file=@${JAR_FILE}"
